server:
  port: 80  servlet:    context-path: /
eureka:
   client:
    register-with-eureka: false #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
      defaultZone: http://eureka2001.dpf.com:2001/eureka/,http://eureka2002.dpf.com:2002/eureka/,http://eureka2003.dpf.com:2003/eureka/ # 集群
    