server:
  port: 1003
spring: 
    application:
      name: MICROSERVICE-USER
    datasource: 
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.0.5:1433;DatabaseName=practice;autoReconnect=true;useLOBs=false
      username: sa
      password: aaa
mybatis: 
    typeAliasesPackage: com.dpf.beans
    mapper-locations: classpath:com/dpf/**/mapper/*.xml 
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-user  #客户端服务名
    instance-id: microservice-user:1003 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
        # 单机 defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone: http://eureka2001.dpf.com:2001/eureka/,http://eureka2002.dpf.com:2002/eureka/,http://eureka2003.dpf.com:2003/eureka/ # 集群
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三
   联系电话: 110  
